Update rest_response.rb
SG API returns this:
```JSON
{  
   "result_ok":true,
   "total_count":"0",
   "page":1,
   "total_pages":0,
   "results_per_page":50,
   "data":[  
      null
   ]
}
```
when requesting survey campaigns.

This causes the error `NoMethodError: undefined method `[]' for nil:NilClass` because `dataum` is `nil`